name: QR Code Scraper

on:
  schedule:
    # Run every 5 minutes (GitHub Actions minimum for scheduled workflows)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-qr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        pip install playwright beautifulsoup4 requests python-dotenv
        python -m playwright install chromium
        python -m playwright install-deps
    
    - name: Run QR scraper
      env:
        RISE_USERNAME: ${{ secrets.RISE_USERNAME }}
        RISE_PASSWORD: ${{ secrets.RISE_PASSWORD }}
      run: |
        python .github/scripts/github_qr_scraper.py
    
    - name: Decode QR code
      run: |
        pip install opencv-python-headless numpy
        python .github/scripts/decode_latest_qr.py || echo "Decoding failed"
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scraped_qr_codes/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-scraped QR code at $(date -u)" && git push)