name: Scrape Rise Gym QR Codes

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
    # Run every 2 hours at 1 minute past the hour (00:01, 02:01, 04:01, etc.)
    - cron: '1 */2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        python -m playwright install chromium
        python -m playwright install-deps
    
    - name: Run QR scraper
      env:
        RISE_GYM_EMAIL: ${{ secrets.RISE_GYM_EMAIL }}
        RISE_GYM_PASSWORD: ${{ secrets.RISE_GYM_PASSWORD }}
      run: |
        python src/utils/qr_scraper.py
    
    - name: Generate QR manifest
      run: |
        python generate_qr_manifest.py
    
    - name: Upload to Firebase
      if: success()
      env:
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
      run: |
        python src/utils/firebase_uploader.py || echo "Firebase upload failed (non-critical)"
    
    - name: Upload debug artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-screenshots
        path: |
          debug_ci_after_login.png
          *.png
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "lukaj99@users.noreply.github.com"
        git config --local user.name "lukaj99"
        # Add all changes first
        git add -f real_qr_codes/*.svg
        git add -f real_qr_codes/manifest.json
        git add src/data/*.json
        # Check if there are changes to commit
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update QR codes [skip ci]"
          git pull --rebase
          git push
        fi