name: Scrape Rise Gym QR Codes

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        python -m playwright install chromium
        python -m playwright install-deps
    
    - name: Run QR scraper
      env:
        RISE_GYM_EMAIL: ${{ secrets.RISE_GYM_EMAIL }}
        RISE_GYM_PASSWORD: ${{ secrets.RISE_GYM_PASSWORD }}
      run: |
        python src/utils/qr_scraper.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add real_qr_codes/*.svg
        git add src/data/*.json
        git diff --staged --quiet || (git commit -m "Auto-update QR codes [skip ci]" && git push)